name: Deploy MkDocs
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-jupyter mkdocs-include-markdown-plugin
      
      - name: Debug Information
        run: |
          pwd
          ls -R docs
          cat mkdocs.yml
      
      - name: Build MkDocs Site
        run: |
          mkdocs build --verbose
      
      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
